# Generated by Django 6.1 on 2026-08-22 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('email', models.EmailField(help_text='Dùng làm tên đăng nhập', max_length=255, unique=True, verbose_name='Địa chỉ email')),
                ('full_name', models.CharField(help_text='Họ tên đầy đủ của người dùng', max_length=255, verbose_name='Họ và tên')),
                ('role', models.CharField(choices=[('STUDENT', 'Học viên'), ('TEACHER', 'Giáo viên'), ('ADMIN', 'Quản trị viên')], default='STUDENT', help_text='Phân quyền trong hệ thống', max_length=20, verbose_name='Vai trò')),
                ('level', models.CharField(choices=[('A1', 'A1 - Beginner (Mới bắt đầu)'), ('A2', 'A2 - Elementary (Sơ cấp)'), ('B1', 'B1 - Intermediate (Trung cấp)'), ('B2', 'B2 - Upper-Intermediate (Trung cao cấp)'), ('C1', 'C1 - Advanced (Cao cấp)'), ('C2', 'C2 - Proficiency (Thành thạo)')], default='A1', help_text='Trình độ hiện tại theo khung CEFR', max_length=10, verbose_name='Trình độ tiếng Anh')),
                ('avatar_url', models.URLField(blank=True, help_text='Đường dẫn ảnh đại diện', max_length=500, null=True, verbose_name='Ảnh đại diện')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Tiểu sử ngắn')),
                ('is_active', models.BooleanField(default=True, help_text='Chỉ định xem tài khoản này có được phép đăng nhập hay không.', verbose_name='Trạng thái hoạt động')),
                ('is_staff', models.BooleanField(default=False, help_text='Chỉ định xem người dùng có thể đăng nhập vào trang admin hay không.', verbose_name='Quyền truy cập Admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Danh sách người dùng',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
