# Generated by Django 6.0.5 on 2026-10-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Học viên'), ('TEACHER', 'Giáo viên'), ('REVIEWER', 'Người phản biện / Thẩm định bài giảng'), ('ADMIN', 'Quản trị viên')], default='STUDENT', help_text='Phân quyền trong hệ thống', max_length=20, verbose_name='Vai trò'),
        ),
    ]
