# Generated by Django 6.1 on 2026-09-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='target_level',
            field=models.CharField(choices=[('A1', 'A1 - Beginner (Mới bắt đầu)'), ('A2', 'A2 - Elementary (Sơ cấp)'), ('B1', 'B1 - Intermediate (Trung cấp)'), ('B2', 'B2 - Upper-Intermediate (Trung cao cấp)'), ('C1', 'C1 - Advanced (Cao cấp)'), ('C2', 'C2 - Proficiency (Thành thạo)'), ('ALL', 'Mọi trình độ')], default='ALL', max_length=10, verbose_name='Trình độ tiếng Anh mục tiêu'),
        ),
    ]
