# Generated by Django 6.1 on 2026-09-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail_url',
            field=models.TextField(blank=True, help_text='Đường dẫn ảnh đại diện hoặc dữ liệu Base64', null=True, verbose_name='Ảnh đại diện khóa học'),
        ),
    ]
