# Generated by Django 6.1 on 2026-09-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.TextField(blank=True, help_text='YouTube URL hoặc dữ liệu video tải từ máy', null=True, verbose_name='Đường dẫn video bài giảng hoặc Base64/File'),
        ),
    ]
