# Generated by Django 6.0.5 on 2026-09-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file_url',
            field=models.TextField(blank=True, help_text='Đường dẫn tệp hoặc dữ liệu Base64 đính kèm', null=True, verbose_name='Đường dẫn tệp tài liệu hoặc dữ liệu Base64'),
        ),
    ]
