# Generated by Django 6.0.5 on 2026-09-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_material_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Phản hồi từ Quản trị viên khi từ chối khóa học', null=True, verbose_name='Lý do từ chối phê duyệt'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PENDING', 'Chờ duyệt'), ('PUBLISHED', 'Đã xuất bản'), ('REJECTED', 'Bị từ chối'), ('ARCHIVED', 'Đã lưu trữ')], default='DRAFT', max_length=20, verbose_name='Trạng thái khóa học'),
        ),
    ]
