# Generated by Django 6.0.5 on 2026-10-03 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_rejection_reason_alter_course_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thẩm định'),
        ),
        migrations.AddField(
            model_name='course',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_courses', to=settings.AUTH_USER_MODEL, verbose_name='Người thẩm định / Phản biện'),
        ),
        migrations.AlterField(
            model_name='course',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Ý kiến phản biện từ Thẩm định viên / Quản trị viên khi từ chối khóa học', null=True, verbose_name='Lý do từ chối / Phản biện khóa học'),
        ),
    ]
