# Generated by Django 6.0.5 on 2026-10-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_reviewed_at_course_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_resubmitted',
            field=models.BooleanField(default=False, help_text='Đánh dấu giảng viên đã cập nhật lại nội dung và gửi duyệt lại cho phản biện', verbose_name='Đã gửi duyệt lại sau phản biện'),
        ),
        migrations.AddField(
            model_name='course',
            name='previous_rejection_reason',
            field=models.TextField(blank=True, help_text='Lưu vết nhận xét phản biện cũ để đối chiếu kiểm tra khi giảng viên gửi lại', null=True, verbose_name='Ý kiến phản biện lần trước'),
        ),
        migrations.AddField(
            model_name='course',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian gửi duyệt lại'),
        ),
    ]
