# Generated by Django 6.0.5 on 2026-09-02 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_question_level_alter_quiz_level'),
        ('courses', '0004_alter_material_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='courses.chapter', verbose_name='Chương học liên kết'),
        ),
    ]
