# Generated by Django 6.0.5 on 2026-09-04 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_quiz_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('topic', models.CharField(max_length=255, verbose_name='Chủ đề học thuật')),
                ('sub_topic', models.CharField(blank=True, default='', max_length=255, verbose_name='Chủ đề phụ cụ thể')),
                ('skill', models.CharField(blank=True, default='GRAMMAR', max_length=50, verbose_name='Kỹ năng đánh giá')),
                ('difficulty', models.CharField(blank=True, default='B1', max_length=20, verbose_name='Độ khó CEFR')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Lý giải chuyên sâu từ AI')),
                ('confidence', models.FloatField(default=0.0, verbose_name='Độ tin cậy của AI (0.0 - 1.0)')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu JSON gốc từ LLM')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='assessments.question', verbose_name='Câu hỏi được phân tích')),
            ],
            options={
                'verbose_name': 'Phân tích AI cho câu hỏi',
                'verbose_name_plural': 'Danh sách phân tích AI câu hỏi',
                'db_table': 'question_ai_analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
