# Generated by Django 6.0.5 on 2026-09-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_questionaianalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Đã luyện tập khắc phục'),
        ),
    ]
