# Generated by Django 6.1 on 2026-08-30 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_alter_question_level_alter_quiz_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('title', models.CharField(default='Phiên nhập đề thi tự động', max_length=255, verbose_name='Tên phiên import')),
                ('source_type', models.CharField(choices=[('RAW_TEXT', 'Văn bản thô / Dán trực tiếp'), ('DOCX', 'Tệp Microsoft Word (.docx)'), ('XLSX', 'Tệp Microsoft Excel (.xlsx)'), ('CSV', 'Tệp bảng tính (.csv)')], default='RAW_TEXT', max_length=20, verbose_name='Nguồn dữ liệu')),
                ('file', models.FileField(blank=True, null=True, upload_to='quiz_imports/%Y/%m/', verbose_name='Tệp đính kèm (.docx, .xlsx, .csv)')),
                ('raw_text', models.TextField(blank=True, default='', verbose_name='Nội dung văn bản thô')),
                ('use_ai', models.BooleanField(default=False, help_text='Bật tùy chọn này để AI tự động nhận diện và bóc tách câu hỏi phức tạp', verbose_name='Sử dụng Google Gemini AI trích xuất')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ phân tích cú pháp'), ('PARSED', 'Đã trích xuất (Chờ giáo viên xác nhận)'), ('IMPORTED', 'Đã import thành công vào Đề thi'), ('FAILED', 'Trích xuất thất bại')], default='PENDING', max_length=20, verbose_name='Trạng thái phiên import')),
                ('total_parsed', models.PositiveIntegerField(default=0, verbose_name='Số câu hỏi trích xuất thành công')),
                ('total_imported', models.PositiveIntegerField(default=0, verbose_name='Số câu hỏi đã lưu vào đề thi')),
                ('parsed_data', models.JSONField(blank=True, default=list, help_text='Chứa danh sách câu hỏi, dạng câu, các phương án và đáp án đúng', verbose_name='Dữ liệu câu hỏi đã chuẩn hóa (JSON)')),
                ('error_log', models.TextField(blank=True, default='', verbose_name='Nhật ký lỗi (nếu có)')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='assessments.quiz', verbose_name='Đề thi đích')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên thực hiện')),
            ],
            options={
                'verbose_name': 'Phiên import đề thi',
                'verbose_name_plural': 'Quản lý Phiên import đề thi',
                'db_table': 'quiz_import_batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
