# Generated by Django 6.1 on 2026-08-30 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_alter_question_level_alter_quiz_level'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('title', models.CharField(default='Lộ trình học tập tiếng Anh cá nhân hóa', max_length=255, verbose_name='Tiêu đề lộ trình')),
                ('target_level', models.CharField(choices=[('A1', 'A1 - Beginner (Mới bắt đầu)'), ('A2', 'A2 - Elementary (Sơ cấp)'), ('B1', 'B1 - Intermediate (Trung cấp)'), ('B2', 'B2 - Upper-Intermediate (Trung cao cấp)'), ('C1', 'C1 - Advanced (Cao cấp)'), ('C2', 'C2 - Proficiency (Thành thạo)')], default='B2', max_length=10, verbose_name='Trình độ mục tiêu')),
                ('current_estimated_level', models.CharField(choices=[('A1', 'A1 - Beginner (Mới bắt đầu)'), ('A2', 'A2 - Elementary (Sơ cấp)'), ('B1', 'B1 - Intermediate (Trung cấp)'), ('B2', 'B2 - Upper-Intermediate (Trung cao cấp)'), ('C1', 'C1 - Advanced (Cao cấp)'), ('C2', 'C2 - Proficiency (Thành thạo)')], default='B1', max_length=10, verbose_name='Trình độ hiện tại ước tính')),
                ('goal_description', models.TextField(blank=True, verbose_name='Mục tiêu & Kỳ vọng học tập')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'Đang thực hiện'), ('COMPLETED', 'Đã hoàn thành'), ('ARCHIVED', 'Đã lưu trữ / Thay thế')], default='IN_PROGRESS', max_length=20, verbose_name='Trạng thái lộ trình')),
                ('total_steps', models.PositiveIntegerField(default=0, verbose_name='Tổng số chặng/bước')),
                ('completed_steps', models.PositiveIntegerField(default=0, verbose_name='Số chặng đã hoàn thành')),
                ('progress_percentage', models.FloatField(default=0.0, verbose_name='Tiến độ hoàn thành (%)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL, verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Lộ trình học tập',
                'verbose_name_plural': 'Quản lý Lộ trình học tập AI',
                'db_table': 'rec_learning_paths',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('step_index', models.PositiveIntegerField(default=1, verbose_name='Thứ tự chặng')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề chặng học')),
                ('description', models.TextField(blank=True, verbose_name='Hướng dẫn chi tiết từ AI')),
                ('step_type', models.CharField(choices=[('COURSE', 'Học toàn bộ khóa học'), ('LESSON', 'Học bài học trọng tâm'), ('QUIZ', 'Làm bài kiểm tra đánh giá'), ('AI_PRACTICE', 'Luyện tập tương tác với Trợ lý AI')], default='COURSE', max_length=20, verbose_name='Loại hành động')),
                ('target_skill', models.CharField(choices=[('LISTENING', 'Kỹ năng Nghe'), ('READING', 'Kỹ năng Đọc'), ('WRITING', 'Kỹ năng Viết'), ('SPEAKING', 'Kỹ năng Nói'), ('GRAMMAR', 'Ngữ pháp'), ('VOCABULARY', 'Từ vựng')], default='GRAMMAR', max_length=20, verbose_name='Kỹ năng trọng tâm cần rèn luyện')),
                ('estimated_minutes', models.PositiveIntegerField(default=30, verbose_name='Thời gian ước tính (phút)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Đã hoàn thành')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm hoàn thành')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recommendations.learningpath', verbose_name='Lộ trình học tập')),
                ('target_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_steps', to='courses.course', verbose_name='Khóa học mục tiêu')),
                ('target_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_steps', to='courses.lesson', verbose_name='Bài học mục tiêu')),
                ('target_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_steps', to='assessments.quiz', verbose_name='Bài kiểm tra mục tiêu')),
            ],
            options={
                'verbose_name': 'Chặng học trong lộ trình',
                'verbose_name_plural': 'Danh sách Chặng học lộ trình',
                'db_table': 'rec_learning_path_steps',
                'ordering': ['step_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('relevance_score', models.FloatField(default=90.0, verbose_name='Điểm tương thích/phù hợp (0 - 100)')),
                ('reason', models.TextField(verbose_name='Lý do AI đề xuất khóa học')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='Học viên đã ẩn/bỏ qua gợi ý')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='courses.course', verbose_name='Khóa học được đề xuất')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Gợi ý Khóa học AI',
                'verbose_name_plural': 'Danh sách Gợi ý Khóa học AI',
                'db_table': 'rec_course_recommendations',
                'ordering': ['-relevance_score', '-created_at'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('skill_type', models.CharField(choices=[('LISTENING', 'Kỹ năng Nghe'), ('READING', 'Kỹ năng Đọc'), ('WRITING', 'Kỹ năng Viết'), ('SPEAKING', 'Kỹ năng Nói'), ('GRAMMAR', 'Ngữ pháp'), ('VOCABULARY', 'Từ vựng')], max_length=20, verbose_name='Kỹ năng ngôn ngữ')),
                ('proficiency_score', models.FloatField(default=0.0, verbose_name='Điểm thành thạo năng lực (0 - 100)')),
                ('weak_topics', models.JSONField(blank=True, default=list, help_text="Ví dụ: ['Past Simple vs Present Perfect', 'Prepositions of Place']", verbose_name='Danh sách các chủ đề/dạng bài còn yếu')),
                ('recommended_action', models.TextField(blank=True, verbose_name='Đề xuất cải thiện từ AI')),
                ('last_assessed_at', models.DateTimeField(auto_now=True, verbose_name='Lần đánh giá gần nhất')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to=settings.AUTH_USER_MODEL, verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Phân tích Lỗ hổng Kỹ năng',
                'verbose_name_plural': 'Bảng Phân tích Lỗ hổng Kỹ năng Học viên',
                'db_table': 'rec_skill_gap_analyses',
                'ordering': ['proficiency_score'],
                'unique_together': {('student', 'skill_type')},
            },
        ),
    ]
