# Generated by Django 6.0.5 on 2026-09-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgapanalysis',
            name='is_assessed',
            field=models.BooleanField(default=False, verbose_name='Đã được đánh giá qua bài thi'),
        ),
        migrations.AlterField(
            model_name='skillgapanalysis',
            name='proficiency_score',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Điểm thành thạo năng lực (0 - 100)'),
        ),
        migrations.AlterField(
            model_name='skillgapanalysis',
            name='weak_topics',
            field=models.JSONField(blank=True, default=list, help_text="Ví dụ: [{'topic': 'Past Perfect', 'sub_topic': 'Past Perfect vs Past Simple'}]", verbose_name='Danh sách các chủ đề/dạng bài còn yếu'),
        ),
    ]
