# Generated by Django 6.0.5 on 2026-09-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_skillgapanalysis_is_assessed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningpath',
            name='student',
        ),
        migrations.RemoveField(
            model_name='learningpathstep',
            name='learning_path',
        ),
        migrations.RemoveField(
            model_name='learningpathstep',
            name='target_course',
        ),
        migrations.RemoveField(
            model_name='learningpathstep',
            name='target_lesson',
        ),
        migrations.RemoveField(
            model_name='learningpathstep',
            name='target_quiz',
        ),
        migrations.AlterUniqueTogether(
            name='skillgapanalysis',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skillgapanalysis',
            name='student',
        ),
        migrations.DeleteModel(
            name='CourseRecommendation',
        ),
        migrations.DeleteModel(
            name='LearningPath',
        ),
        migrations.DeleteModel(
            name='LearningPathStep',
        ),
        migrations.DeleteModel(
            name='SkillGapAnalysis',
        ),
    ]
